CREATE TABLE IF NOT EXISTS forge_catalog_finished_hats (
    id CHAR(36) NOT NULL,
    finished_hat_name VARCHAR(255) NOT NULL,
    photo_path VARCHAR(255) DEFAULT NULL,
    image_width INT UNSIGNED DEFAULT NULL,
    image_height INT UNSIGNED DEFAULT NULL,
    design_id CHAR(36) DEFAULT NULL,
    hat_id CHAR(36) DEFAULT NULL,
    material_id CHAR(36) DEFAULT NULL,
    patch_shape VARCHAR(120) DEFAULT NULL,
    patch_size VARCHAR(120) DEFAULT NULL,
    placement_status VARCHAR(40) NOT NULL DEFAULT 'unassigned',
    location_label VARCHAR(255) DEFAULT NULL,
    retail_price DECIMAL(10,2) DEFAULT NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'review',
    notes TEXT DEFAULT NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    KEY idx_forge_catalog_finished_hats_updated_at (updated_at),
    KEY idx_forge_catalog_finished_hats_status (status),
    KEY idx_forge_catalog_finished_hats_placement_status (placement_status),
    KEY idx_forge_catalog_finished_hats_design_id (design_id),
    KEY idx_forge_catalog_finished_hats_hat_id (hat_id),
    KEY idx_forge_catalog_finished_hats_material_id (material_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
